// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.geo.provider.use_gpsd", true);
user_pref("app.normandy.user_id", "ab304633-d238-47cb-be28-235b5e5c4f08");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1558521768);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1558521888);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558613815);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1558521648);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1558522128);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558613877);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1558522248);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1558522008);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1558519621);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8929b783-fc38-4f7f-9462-74f37f5d2ae9}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1558569600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558613789856");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558615560856");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558613790478");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558617390478");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.countryCode", "IE");
user_pref("browser.search.region", "IE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327133223");
user_pref("browser.slowStartup.averageTime", 1577);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "google.com");
user_pref("browser.startup.homepage_override.buildID", "20190327133223");
user_pref("browser.startup.homepage_override.mstone", "60.6.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1558519623163");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.6.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.redhat.bookmarksProcessed", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Tue, 21 May 2019 10:28:38 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1558521769);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327133223");
user_pref("extensions.lastAppVersion", "60.6.1");
user_pref("extensions.lastPlatformVersion", "60.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"3a5f14d3-aa1c-497b-b459-7c3175fe6a5a\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1558521743);
user_pref("media.gmp-manager.buildID", "20190327133223");
user_pref("media.gmp-manager.lastCheck", 1558521544);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1558521743);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "157801da-e507-4440-b1fd-15d2611e7a04");
user_pref("services.blocklist.addons.checked", 1558521883);
user_pref("services.blocklist.clock_skew_seconds", 5);
user_pref("services.blocklist.gfx.checked", 1558521883);
user_pref("services.blocklist.last_etag", "\"1558483216037\"");
user_pref("services.blocklist.last_update_seconds", 1558521883);
user_pref("services.blocklist.onecrl.checked", 1558521883);
user_pref("services.blocklist.pinning.checked", 1558521883);
user_pref("services.blocklist.plugins.checked", 1558521883);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1558521743);
user_pref("toolkit.startup.last_success", 1558613846);
user_pref("toolkit.telemetry.cachedClientID", "f9644674-16e0-4220-b2b7-282aa85e987b");
user_pref("toolkit.telemetry.previousBuildID", "20190327133223");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
